// PSGameMapTests.cpp -- Epic 146.2: the default level exists, loads, and boots the match
//
// Tests covered:
//   1. GameDefaultMap (/Game/Maps/GameMap, generated by tools/content_pipeline's game_map step)
//      is a real level in this checkout, not a Git LFS pointer file. It loads as a world. Its
//      GameMode Override is the match (APSGameMode), which Play Now relies on: it travels to the
//      level without a game option. Its daylight needs no lighting build (a movable sun and sky
//      light, a sky atmosphere), and it has a player start and the field grid (146.3), which builds
//      the field from data at BeginPlay.

#include "CoreMinimal.h"
#include "Misc/AutomationTest.h"
#include "Components/LightComponent.h"
#include "Components/SkyAtmosphereComponent.h"
#include "Engine/DirectionalLight.h"
#include "Engine/Level.h"
#include "Engine/SkyLight.h"
#include "Engine/World.h"
#include "GameFramework/PlayerStart.h"
#include "GameFramework/WorldSettings.h"
#include "GameMapsSettings.h"
#include "HAL/FileManager.h"
#include "Misc/PackageName.h"
#include "PSFieldGrid.h"
#include "PSGameMode.h"
#include "UObject/Package.h"
#include "UObject/UObjectGlobals.h"

#if WITH_DEV_AUTOMATION_TESTS

namespace PSGameMapTests
{
    /** A Git LFS pointer file is a few lines of text; any real level is far larger. */
    const int64 LargestPointerFileBytes = 1024;

    template <typename ActorType>
    int32 CountActors(const ULevel& Level)
    {
        int32 Count = 0;
        for (AActor* Actor : Level.Actors)
        {
            Count += Cast<ActorType>(Actor) ? 1 : 0;
        }
        return Count;
    }
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
    FPSGameMapTest,
    "PlaySports.Content.GameMap",
    EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)

bool FPSGameMapTest::RunTest(const FString& Parameters)
{
    using namespace PSGameMapTests;

    const FString MapPackage = UGameMapsSettings::GetGameDefaultMap();
    TestEqual(TEXT("The game boots into /Game/Maps/GameMap"), MapPackage, FString(TEXT("/Game/Maps/GameMap")));

    FString MapFile;
    if (!TestTrue(TEXT("...which exists"), FPackageName::DoesPackageExist(MapPackage, &MapFile)))
    {
        return false;
    }
    if (!TestTrue(TEXT("...as a real level, not a Git LFS pointer (check out with LFS)"), IFileManager::Get().FileSize(*MapFile) > LargestPointerFileBytes))
    {
        return false;
    }

    UPackage* Package = LoadPackage(nullptr, *MapPackage, LOAD_None);
    UWorld* MapWorld = Package ? UWorld::FindWorldInPackage(Package) : nullptr;
    if (!TestNotNull(TEXT("...and loads as a world"), MapWorld) || !TestNotNull(TEXT("...with its level"), MapWorld->PersistentLevel.Get()))
    {
        return false;
    }
    const ULevel& Level = *MapWorld->PersistentLevel;

    const AWorldSettings* Settings = Level.GetWorldSettings(false);
    TestTrue(TEXT("Its GameMode Override is the match: Play Now travels to it without a game option"),
        Settings && Settings->DefaultGameMode.Get() == APSGameMode::StaticClass());

    int32 MovableSuns = 0;
    int32 MovableSkyLights = 0;
    for (AActor* Actor : Level.Actors)
    {
        const ALight* Light = Cast<ALight>(Actor);
        const ULightComponent* LightComponent = Light ? Light->GetLightComponent() : nullptr;
        if (Cast<ADirectionalLight>(Actor) && LightComponent && LightComponent->Mobility == EComponentMobility::Movable)
        {
            ++MovableSuns;
        }
        const ASkyLight* Sky = Cast<ASkyLight>(Actor);
        const USceneComponent* SkyRoot = Sky ? Sky->GetRootComponent() : nullptr;
        if (SkyRoot && SkyRoot->Mobility == EComponentMobility::Movable)
        {
            ++MovableSkyLights;
        }
    }
    TestEqual(TEXT("One sun, movable: no lighting build"), MovableSuns, 1);
    TestEqual(TEXT("One sky light, movable"), MovableSkyLights, 1);
    TestEqual(TEXT("One sky atmosphere"), CountActors<ASkyAtmosphere>(Level), 1);
    TestEqual(TEXT("One player start"), CountActors<APlayerStart>(Level), 1);
    TestEqual(TEXT("One field grid, which builds the field from data at BeginPlay"), CountActors<APSFieldGrid>(Level), 1);
    return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
