// PSLocalization.h - Epic 106: user-facing text through UE's localization system
#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "PSLocalization.generated.h"

class UPSSettingsSubsystem;

/** How heights and weights are shown: the Units setting's choices, in order. */
UENUM(BlueprintType)
enum class EPSUnitSystem : uint8
{
    /** Feet and inches, pounds. */
    Imperial,
    /** Centimeters, kilograms. */
    Metric
};

/**
 * UPSLocalization is the one way user-facing text reaches the screen (Epic 106). UE's gather
 * collects both of its string tables, so a translation needs no code change.
 *
 * Three kinds of text go through it:
 *   - The code's own text. GetText/Format read the "PSUI" string table, Data/ui_text.csv
 *     (hand-written: "Reset to defaults", "{Label}: {Value}", unit patterns, HUD banners,
 *     input action names).
 *   - The UI data files' text. GetDataText reads the "PSUIData" table, Data/ui_text_data.csv.
 *     It is generated from ui_menus.json, ui_settings.json and loading_tips.json by
 *     tools/ui_text.py, and validate_data.py fails when it is stale. The keys are
 *     MenuKey/SettingKey/TipKey. A string missing from it, or changed since it was
 *     generated, is shown as written, untranslated.
 *   - Text that is not ours to translate: team and player names, button labels, text the
 *     engine already localized. Verbatim says so.
 *
 * Presenters (UPSMenuComponent::GetPresentedScreen) localize as they build a screen, so
 * widgets receive localized strings and show them with FromLocalized. tools/validate_data.py
 * rejects FText built from raw strings in UI code (PSUI*, PSMenu*, PSHUD*, PSLoading*,
 * PSSettings*), and the review-verify skill asks the same of every other user-facing file.
 *
 * Pseudo-localization (ps.Loc.Pseudo 1, or SetPseudoLocalization) swaps every letter of the
 * text that came through the tables for an accented one, pads it by a third and brackets it,
 * so "Reset to defaults" still reads but is never plain ASCII. Verbatim text is marked with
 * single angle quotes (U+2039, U+203A) instead.
 * Anything still plain on screen bypassed this class. IsFullyLocalized checks a string for
 * that.
 *
 * Formatting follows the current culture: numbers, percentages and dates through FText, and
 * heights and weights in the player's units (the Units setting, Data/ui_settings.json).
 */
UCLASS()
class PLAYSPORTS_API UPSLocalization : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

public:
    /** The code's own text: Data/ui_text.csv. */
    static const FName UITableId;

    /** The UI data files' text: Data/ui_text_data.csv, generated by tools/ui_text.py. */
    static const FName DataTableId;

    /** The setting that picks EPSUnitSystem (Data/ui_settings.json). */
    static const FName UnitsSettingId;

    /** Registers both string tables from their CSV files, once. Every lookup calls it. */
    static void RegisterStringTables();

    /** Whether the PSUI table has Key. */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static bool HasText(const FString& Key);

    /** PSUI's text for Key. A missing key shows as "<Key>" and logs a warning;
     *  validate_data.py checks that every key the code names exists. */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static FText GetText(const FString& Key);

    /** PSUI's pattern for Key, formatted with Arguments ({Name} placeholders). */
    static FText Format(const FString& Key, const FFormatNamedArguments& Arguments);

    /** A UI data file's string: PSUIData's text for Key when the table holds Source there,
     *  else Source as written. */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static FText GetDataText(const FString& Key, const FString& Source);

    /** Text that is not ours to translate: a name, a button label, the engine's own text. */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static FText Verbatim(const FString& Text);

    /** A string a presenter has already localized through this class, for a widget. */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static FText FromLocalized(const FString& Localized);

    /** Lines one under another. */
    static FText JoinLines(const TArray<FText>& Lines);

    /** PSUIData keys. These are the same keys tools/ui_text.py generates:
     *  Menu.<ScreenId>.Title|Body, Menu.<ScreenId>.<OptionId>.Label|Detail,
     *  Setting.Category.<CategoryId>, Setting.<SettingId>.Label|Description|Unit,
     *  Setting.<SettingId>.Choice<Index>, Tip.<TipId>. */
    static FString MenuKey(FName ScreenId, const FString& Field);
    static FString MenuOptionKey(FName ScreenId, FName OptionId, const FString& Field);
    static FString SettingCategoryKey(FName CategoryId);
    static FString SettingKey(FName SettingId, const FString& Field);
    static FString SettingChoiceKey(FName SettingId, int32 Index);
    static FString TipKey(FName TipId);

    /** Turns pseudo-localization on or off (the ps.Loc.Pseudo console variable). */
    UFUNCTION(BlueprintCallable, Category = "Localization")
    static void SetPseudoLocalization(bool bOn);

    UFUNCTION(BlueprintPure, Category = "Localization")
    static bool IsPseudoLocalization();

    /** Text as pseudo-localization shows it: letters accented ({placeholders} kept), a third
     *  longer, bracketed. */
    static FString PseudoLocalize(const FString& Text);

    /** True when Shown has no plain letter outside Verbatim's marks, meaning that under
     *  pseudo-localization everything in it came through this class. */
    static bool IsFullyLocalized(const FString& Shown);

    /** Value in the current culture (or Culture): grouping, decimal mark, at most
     *  MaxFractionalDigits decimals. */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static FText FormatNumber(float Value, int32 MaxFractionalDigits);
    static FText FormatNumberIn(float Value, int32 MaxFractionalDigits, const FCulturePtr& Culture);

    /** Fraction (1 = 100%) as the culture writes a percentage. */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static FText FormatPercent(float Fraction);

    /** Date (no time zone shift) as the culture writes it, medium length. */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static FText FormatDate(const FDateTime& Date);

    /** A player's weight (FPlayerAttributes::WeightKg) in Units: "247 lb" or "112 kg". */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static FText FormatWeight(float WeightKg, EPSUnitSystem Units);

    /** A player's height (FPlayerAttributes::HeightCm) in Units: 6' 2" or "188 cm". */
    UFUNCTION(BlueprintPure, Category = "Localization")
    static FText FormatHeight(float HeightCm, EPSUnitSystem Units);

    /** The Units setting in Settings; Imperial without settings. */
    static EPSUnitSystem GetUnitSystem(UPSSettingsSubsystem* Settings);
};
